### ISSUE TITLE
Add a mechanism for shipshape to interrogate the sea-map config

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#155]
Now that the config.json is gone, and use use a javascript config, there needs to be something which exposes that to shipshape.

**Comment by wu-lee** [comment]
@ColmMassey

**Comment by ColmMassey** [comment]
The simplest solution may be for a config.json file to also be generated mirroring what is in the Truescript, but compatible with old format, so shipshape still works.

**Comment by wu-lee** [comment]
This is now implemented and a working version of shipshape deployed on https://dev-1.solidarityeconomy.coop/shipshape/

Latest versions of the coops-uk map has a version of mykomap which exports metadata in a `config.json` file that sea-map can retrieve.  It no longer has version.json and `about.html`, however - this information is included in `config.json`.  The version this begins working on is v3.0.2.

Some values of the version.json fields, as well as being moved to config.json, have been renamed to mirror the projects renaming to mykomap. For instance, `version.seaMapVersion`, and `version.seaMapResolvedVersion`.

sea-map v2.x and mykomap v3.0.0 and v3.0.1 do not provide all (or any) information for shipshape.  The production version of coops-uk and obo-public maps still use these.

Therefore shipshape needed to be updated to be aware of these variations, and deal with them accordingly. 

On the new version of shipshape, you should see that:
- Field names are not sea-map specific (speicifcally, "sea-map version" is now "code version", internally names have been changed also)
- Shipshape's proxy (which obtains the data) is now able to query sea-map and mykomap metadata for all versions (where this data is available)
- Partial support for multiple datasets has been added.  However, endpoint/DGU and query are only shown for the first dataset.

**Comment by ColmDC** [comment]
Nice. Is there a missing line at the bottom? Is it perhaps the prod version of the oxford project?

**Comment by wu-lee** [comment]
I can see lines with the prod and dev version of Oxford?

What are missing are those 2.x projects, which mostly don't expose any information.

**Comment by ColmDC** [comment]
> I can see lines with the prod and dev version of Oxford?

It has returned. All good.
