### ISSUE TITLE
Text search broken in Mykomap

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/mykomap#158]
In latest iteration of coopsuk map, https://dev.coopsuk.solidarityeconomy.coop/

text search no longer returns any results. 

sea-map@2.0.0_79d3996-dev

"Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[content.js:2](moz-extension://52048f60-2e9e-424b-8596-e881d0b75995/content.js)
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[content.js:2](moz-extension://52048f60-2e9e-424b-8596-e881d0b75995/content.js)
    sendUnloadMessage moz-extension://52048f60-2e9e-424b-8596-e881d0b75995/content.js:2
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 [background.js:1](moz-extension://a88b46d6-a272-4e9b-bb3e-de26a088d7d3/js/background.js)
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist."

**Comment by wu-lee** [comment]
The call to code which adds the generated `searchstr` property to initiatives has been omitted in previous refactoring. Reinstated it in d253865530

This seems to fix the text search.

**Comment by ColmDC** [comment]
Works for me on
https://dev.coopsuk.solidarityeconomy.coop/

 sea-map@2.0.0_d253865-dev
