### ISSUE TITLE
Craft new visualisations of Data Factory Flow 

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#162]
For Korea last year we had the a colourful graphic depicting a simple view of the DataFactory flow.  We need this to be split in two, where one shows the flow from formats/plaforms to apis and standardised published data. 

From ![Sausage Factory](https://user-images.githubusercontent.com/108667445/200637193-3d1d4df5-0cfc-4b69-9f1d-effecde94a3b.jpg)

to 

![Sources-Services](https://user-images.githubusercontent.com/108667445/200637265-059d7657-ea9d-4e3e-a6cc-a3db1f48563b.png)

and 

 
![Formats-Platforms](https://user-images.githubusercontent.com/108667445/200637501-13ea3046-81f3-4b8e-9d43-6ef88014d813.png)

**Comment by ColmDC** [comment]
@MelissaMc20 Hoping to have this for my presentation mid next week. Do you think that is doable?

**Comment by MelissaMc20** [comment]
@ColmDC - Yeah should definitely have that ready for you. 

So just to double check, on the first of the two images you've provided you want: Top images changed to icons that a relevant to each new item you've placed (can I check what the ... in the second to last square is?) > links to the data factory > links to the database components > (link or no links to the items underneath?) - or is it no links, with a link in between the 3 & 4th square? 

& Then on the second image, top link to state the same with text saying 'no standards used' > links to data factory > links to data components > new set of square with links going into the compatible icons with text saying 'compatible with a range of standards' > links into now 'mykomaps' & 'landexplorer' with a link going right into a new square with 3rd party applications

Let me know if any of that doesn't make sense & I can jump into a quick call to clarify

**Comment by ColmDC** [comment]
> (can I check what the ... in the second to last square is?

Ah. It shouldn't be in a box. It just needs something to indicate that there are many other possibilities.

**Comment by ColmDC** [comment]
1str Image
> (link or no links to the items underneath? 
YES, Links please, sorry.

**Comment by ColmDC** [comment]
2nd Image: Sorry, here is a another one. 
![Formats-Platforms](https://user-images.githubusercontent.com/108667445/201092948-fb10459d-dc50-4fe2-8dfc-267a1080e682.png)

**Comment by MelissaMc20** [comment]
![Infographic – 2](https://user-images.githubusercontent.com/59023121/201689239-abba5f5f-ac69-427b-acff-d23235058b86.png)


@ColmDC - the second image.. let me know if there's anything you'd like changed - working on the other one now

**Comment by ColmDC** [comment]
Do you think we should have the Mykomap and LandExplorer logos within the red boxes and replace the generic map logos?

**Comment by MelissaMc20** [comment]
![Infographic – 2 - Logo's](https://user-images.githubusercontent.com/59023121/201730317-181fab7d-b0ee-4d7f-bde6-cb6b327e4d3d.png)
![Infographic – 3](https://user-images.githubusercontent.com/59023121/201730334-da730dea-e428-409d-a0a3-7cc7ef9d38f5.png)

@ColmDC Let me know how  these are :)

**Comment by MelissaMc20** [comment]
https://drive.google.com/drive/u/0/folders/1bKfbuQ3YvC3QNSSsoFwDCWAWGEEcAiWa 

They live here
