### ISSUE TITLE
Custom Markers

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#165]
A place to collect all the work designing and implementing custom map markers (number, colour and shape)

**Comment by ColmDC** [comment]
Closed becasue it was corrupt. replaced here....https://github.com/digitalcommons/allthethings#workspaces/megaboard-639bb01fc526ef0010ab662b/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzMTE2
