### ISSUE TITLE
Mykomap clear-filters button doesn't appear do do much?

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#175]
Version: [mykomap@3.0.4_677b5e7-modified-dev](mailto:mykomap@3.0.4_677b5e7-modified-dev)
Deployment: Owned By Oxford public - https://dev.maps.solidarityeconomy.coop/temp/

Browsers:
 - Firefox on Windows

To replicate:

 - load map
 - open the sidebar and select "Energy"
   - this works
 - Press the Clear Filters Button
   - Nothing happens

**Comment by ColmDC** [comment]
This bug seems fixed in mykomap@3.0.4_89c6116-dev
