### ISSUE TITLE
Clicking on an initiative in the sidebar should activate its pop-up

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#180]

**Comment by ColmDC** [comment]
It does centre it in the view and the tool tip does appear, so at least it does draw the user to its location. Dropping priority of the bug.

**Comment by wu-lee** [comment]
The latest tidying and refactoring of the code appears to have fixed this bug magically - clocking on an initiative now opens the pop-up.  I'm not sure what fixed it?

**Comment by ColmDC** [comment]
This does work now in this case in the  build depolyed here

https://dev.maps.solidarityeconomy.coop/temp/obo-public/

v mykomap@3.0.4_0fcdb90-dev

**Comment by ColmDC** [comment]
However it doesn't work in the following case
https://dev.maps.solidarityeconomy.coop/temp/coopsuk/ 
v mykomap@3.0.4_89c6116-dev

Select Energy and Environemnt - > 
Auchrobert Community Energy Society
