### ISSUE TITLE
Add new DotCoop demo map using the data generated from the new JSON format source

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#185]
There's a new data feed as per https://github.com/DigitalCommons/dotcoop-project/issues/33

Create a map which visualises how that data looks on a MykoMap

**Comment by wu-lee** [comment]
Possibly a duplicate of https://github.com/DigitalCommons/dotcoop-project/issues/33?

**Comment by wu-lee** [comment]
There is a map here, which uses the data published by the feed mentioned above.

IDs are now stable. sector and verification status not yet added.

https://dev.maps.solidarityeconomy.coop/temp/dotcoop2023/

**Comment by wu-lee** [comment]
That map got disappeared somehow.  Redeployed it.

**Comment by wu-lee** [comment]
The country code is missing from the address, Jonathan @ac931274 says they're now included in the data, and that there should be a lot more entries. Investigating.

**Comment by wu-lee** [comment]
https://github.com/DigitalCommons/dotcoop-project/issues/33#issuecomment-1645446030

**Comment by wu-lee** [comment]
Ok, there is a lot more data now being displayed in the map, with Country Code correctly allowing the entries to be categorised by country.  However, further to the comments referenced in issue 33 above, the data had to be fixed up and so may be incomplete - so we need to await for the upstream data problem to be resolved, and then the data should be appearing correctly.

**Comment by ColmDC** [comment]
Great to see this! I can see several co-ops with no domains. Not something possible in the past. Is that in the data. See _Future Forward Cooperative Limited_ for example.

**Comment by wu-lee** [comment]
That case is indeed a coop with no domains in the data we get from upstream.

**Comment by ColmDC** [comment]
Where is the data for this map published as html, ttl and csv?

**Comment by ColmDC** [comment]
I have asked the other dotcoop team members to take a look. We should move it to the main dotcoop url after that, and then close this ticket.

**Comment by wu-lee** [comment]
As noted [elsewhere][1] the data is now fixed and updating.

There were the concerns that the address changes will have moved the map pins significantly in some cases - presumably that needs to be checked again before making this live?

[1]: https://github.com/DigitalCommons/dotcoop-project/issues/33#issuecomment-1652333564

**Comment by ColmDC** [comment]
> There were the concerns that the address changes will have moved the map pins significantly in some cases - presumably that needs to be checked again before making this live?

There has not been any reliable evaluation of geocoding before all these changes. Once https://github.com/DigitalCommons/mykomap/issues/210 has been addressed we should start keeping track of it, but not sure of value looking further backward in time.
