### ISSUE TITLE
Use localised text rather than ID when searching for a vocab field

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#193]
**Describe the bug**
When a vocab is listed as a searched field it needs to use the localised text rather than the ID for vocab

**To Reproduce**
1.Go to [this test map](https://dev.maps.solidarityeconomy.coop/temp/obo-public/?searchedFields=name,primaryActivity)
2. Go to Search panel and select FOOD in the primaryActivity field. 
3. There should be about 10 matches
4. Clear filter and then do a test search for FOOD. 

**Expected behavior**
There should be at least as many matches, but there are only 2

**Video**
[AwesomeScreenshot-23_03_2023,11 56 15.webm](https://user-images.githubusercontent.com/108667445/227197243-e4f54925-5909-44ac-8064-741897af7c94.webm)

**Desktop (please complete the following information):**
 - Windows Firefox
 - mykomap@3.0.4_c0ffa8f-dev

**Comment by wu-lee** [comment]
Maybe not? It was always there, however, I just preserved that function. Although it looks less friendly now that we have some things to name which have no localisations - the field IDs.

Happy to remove it though, would mean one less thing to localise, I agree it's not so useful.

**Comment by ColmDC** [comment]
Purge!

**Comment by wu-lee** [comment]
Ok, removed it, and pushed the changes to testing, you should see a commit ID 1c2336e

**Comment by ColmDC** [comment]
So to clarify, if you use the search term _AM60_ it finds all the initiatives with FOOD as a Primary Activity

**Comment by wu-lee** [comment]
The search term `AM60` comes from the drop-down selection, not the text box. But yes - if you selected the appropriate option in the `primaryActivity` field's dropdown. (The text which was removed showed the state of the drop-downs as well as the text field)

If you search for AM60  in the text field, *and* it the `searchableFields` option included `primaryActivity`, this might do what you say right now, but that's a bug - it shouldn't be putting IDs into the search index.

**Comment by ColmDC** [comment]
The later is what I observe.

**Comment by ColmDC** [comment]
"getting text searches to include vocab fields: one, or a very small number of hours"

**Comment by ColmDC** [comment]
Nice. I confirm this worked in mykomap@3.0.4_ddd0fc6-modified-dev
