### ISSUE TITLE
Markers disappearing unexpectedly when selecting from directory

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#194]
**Describe the bug**
When selescting a specific inititiativ from the directory, nearly all the markers disappear and no dialog is displayed.

**To Reproduce**
In https://dev.maps.solidarityeconomy.coop/temp/obo-public/
Select Housing-Rosehill and Iffley Low Carbon

**Expected behavior**
The dialog of that org should appear.

**Screenshots**
https://www.awesomescreenshot.com/video/15867290?key=0d7123b7b5a3f81a56b93c43cd76c6e8

**Desktop (please complete the following information):**
 - Firefox
 - mykomap@3.0.4_c0ffa8f-dev

**Comment by wu-lee** [comment]
Can't reproduce on that URL, latest obo-public testing build `mykomap@3.0.4_1ff1411-modified-dev`. Seems to be working okay?

**Comment by ColmDC** [comment]
It is also worling again for me on mykomap@3.0.4_1ff1411-modified-dev. on firefox and Chrome. So closing.
