### ISSUE TITLE
Filters displying unexpected behavior

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#196]
**Describe the bug**
On OBO map, when selecting Energy from the CombinedAxtivities, no mateches are found, which is un expected.

**To Reproduce**
Run up https://dev.maps.solidarityeconomy.coop/temp/obo-public/

1. Go to Search panel
2. Filter by Energy
3. No matches found

**Expected behavior**
There should be several matches

**Video**
Problem demonstrated here
https://images.zenhubusercontent.com/235323748/773e2849-2d83-4491-b6ea-36bace132ec5/awesomescreenshot_27_03_2023_20_50_30.mp4

**Desktop (please complete thefollowing information):**
 - Windows 10
 - Firefox
 - mykomap@3.0.4_1ff1411-modified-dev

**Additional context**

**Comment by wu-lee** [comment]
Can't reproduce in latest code - looks like it's fixed?

The raw data says, initiatives with Energy category are:
- in Primary Activity:
  - Low Carbon North Oxford
  - Rose Hill and Iffley low Carbon
- in Secondary Activities:
  - Barton Neighbourhood Centre
  - Blackbird Leys Community Larder
  - CAG Oxfordshire
  - Low Carbon West Oxford
  - Owned by Oxford
  - Rose Hill and Iffley low Carbon
  - Tandem Collective
  - Wolvercote Market
- in Combined Activities:
  - Barton Neighbourhood Centre
  - Blackbird Leys Community Larder
  - CAG Oxfordshire
  - Low Carbon North Oxford
  - Low Carbon West Oxford
  - Owned by Oxford
  - Rose Hill and Iffley low Carbon
  - Tandem Collective
  - Wolvercote Market
 
Checking the map, it seems to get these lists correctly for each case.

(Note, checked locally, this version yet to be redeployed with some other fixes, will notify you on element, hopefully later today)

**Comment by ColmDC** [comment]
Working now on mykomap@3.0.4_81d8327-modified-dev
