### ISSUE TITLE
Create redirection service on maps.coop

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#204]
**Describe the solution you'd like**
Create redirection service on maps.coop which will redirect visitors to the maps which currently live on maps.solidarityeconomy.coop and project specific subdomains of solidarityeconomy.coop.

Specifically,
maps.coop/coopsuk -> https://dev.coopsuk.solidarityeconomy.coop
maps.coop/dotcoop2023 -> https://dev.dotcoop.solidarityeconomy.coop

**Comment by wu-lee** [comment]
Do you want maps.coop to be showing dev.solidarityeconomy.coop maps, or should we have maps.coop showing prod.solidarityeconomy.coop maps, and dev.maps.coop showing dev.solidarityeconomy.coop?

**Comment by ColmDC** [comment]
Let's just have simple maps.coop that could point to a dev or a prod server, or in theory anywhere else...

**Comment by ColmDC** [comment]
How much effort is this to do @lin-d-hop ?

**Comment by wu-lee** [comment]
Temp solution agreed - just link to prod-1 server for coops uk embedding.
