### ISSUE TITLE
[Workers.coop] Conduct a Filter on map opening

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#205]
**Please track against the clockify project [Workers.coop]**

## Description
Expand MM configuration options to support the specification of a  ~~text search and or~~ filter combination for when a MM opens. 

## Acceptance Criteria
It is possible to specify the ~~search/~~ filter combination within the configuration file ~~or via URL parameters~~ for the map.
We can demonstrate the workers.coop map opening with only Active co-ops displayed but the filter can be changed to display all co-ops or the other status'.
~~We can demonstrate the dotcoop map opening with only the co-ops that are members of the NCBA displayed~~
The OBO map can be configured to have only the Community Enterprises visible in the map, but the user can change the filter and show all organisations or just the Support Organisations.

**Comment by ColmDC** [comment]
Obviously this could be set in the config file and not just specified via a url argument.

**Comment by ColmDC** [comment]
dependent on https://github.com/DigitalCommons/dotcoop-project/issues/64

**Comment by lin-d-hop** [comment]
Hi @ColmDC 

It sounds like this feature request is the chosen solution to a specific user need.
Just for clarity, is the actual use need something like - 
As someone hosting a mykomap I need to be able to embed a map with a specific location highlighted?
and/or
As a map user I want to  be able to share a specific location using a mykomap

anything else?

Thanks :)

**Comment by ColmDC** [comment]
Do you think that needs more clarification @lin-d-hop or can we move it to Dev Ready?

**Comment by lin-d-hop** [comment]
I'll try chat with @wu-lee to get clear on the spec on this one and will update asap.

**Comment by ColmDC** [comment]
See simplification of the requirements for this feature in description and a change of Acceptance criteria to work on OBO map rather than DotCoop.

**Comment by wu-lee** [comment]
> The user requirements weren't related to locations. (It is already possible to configure opening the map zoomed and panned to a specific location.)

Clarification - location yes, pin, no.

This can be done via config and overridden in the URL. See https://github.com/DigitalCommons/mykomap/blob/master/CONFIG.md

**Comment by wu-lee** [comment]
The Mykomap documentation currently doesn't have a section describing how supplemental fields are added in any detail (there is an example, but little explanation, see CONFIG.md on the current development branch).

That needs to be added, which should then include documentation for how the filters and their defaults are set.

**Comment by ColmDC** [comment]
> Mykomap documentation currently doesn't have...

Have created a placeholder [ticket ](https://github.com/DigitalCommons/mykomap/issues/242) for this @wu-lee.

**Comment by ColmDC** [comment]
> The workers-coop data feed had been filtering out non-live co-ops from the data up to now - I've now also removed that filter on the development feed, so they should be appearing within the next 5-10 minutes.

That is working nicely now.

**Comment by ColmDC** [comment]
The search history seems to be getting nobbled now when applying two filters in a row via the Directory. Not observed when using Serach panel.

**Comment by wu-lee** [comment]
So far as I can see, the directory doesn't really play well with the history. One of the things I found was that the directory would nobble the defaults by simply clearing all the filters when it was opened. When you go back to the filters, the defaults are gone.

This is I think partly a consequence of the directory using a different (older) mechanism for selecting initiatives in the map. I suggested elsewhere we might want to refactor it to use the new mechanism, then it might play better (although we might need to think about what it is expected to do)

Anyway, to make it a bit less weird I altered the behaviour to reset the history when the directory panel is opened/closed, instead of just clearing the filters. This then puts the filters back to the default state when you return.

**Comment by ColmDC** [comment]
>Anyway, to make it a bit less weird I altered the behaviour to reset the history when the directory panel is opened/closed, instead of just clearing the filters. This then puts the filters back to the default state when you return.

So its not a new problem introduced by this function. So shouldn't stop us closing this issue. 

After https://github.com/DigitalCommons/mykomap/issues/230 we can take a fresh look at how the functionality feels to use and decide if/when to schedule refactoring the directory it to use the new mechanism.

**Comment by ColmDC** [comment]
So this function has been demonstrated working as expected on on Workers.coop.
Let's test it on the other example in the Acceptance Criteria, 

"The OBO map can be configured to have only the Community Enterprises visible in the map, but the user can change the filter and show all organisations or just the Support Organisations."

**Comment by wu-lee** [comment]
Ok, I've bumped the mykomap version used in the obo-public map to 3.1.6 and added the config. Result deployed here:

https://dev.maps.solidarityeconomy.coop/obo-public/
