### ISSUE TITLE
Publish working draft of Workers.coop MykoMap

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#207]
## Description
[Workers.coop]
Using the data we get from worker.coop CiviCRM stream, publish a MykoMap.
Configure the map to use the following styles

Font
Arial or Rubik for Normal text body. Titles, headings and stand-out text in Rubik.
 
Text Size Black or Extra bold for titles, and Rubik
11 or 12 for Normal text body. For titles, depending on document type 40 or 18.
 
Colours
Our colour is Pantone 2012 which breaks down as rgb (239,150,0) , #ef9600 and black, with Pantone used for headings, subheadings, and other stand out features.
 
Headings
Headings and titles can  be in Bold Pantone 2012.

## Acceptance Criteria
 - A map of the data is published at https://dev.maps.coop/workers-coop/
 - All the following fields are displayed for each co-op
   - "Name"
     - "Website"
     - “Industry” [Organisation extras: Industry Sector]
     - “Sic Code” [Sic Code]
     - “Ownership type” [Organisation extras: Ownership type]
     - “Legal form” [Organisation extras: Legal Form]
     - “Registered Number” [Registered Number]
     - “Status” [Organisation extras: Registered Status]
     - [Organisation extras: Description]
 - Contact
   - Street Address
   - Supplemental Address 1	
   - Supplemental Address 2	
   - City	
   - Postal Code
   - Email
 - Industry Sector is used for the Primary Directory 
 - The following filters are used
   - Industry” [Organisation extras: Industry Sector]
   - “Ownership type” [Organisation extras: Ownership type]
   -“Legal form” [Organisation extras: Legal Form]
   -“Status” [Organisation extras: Registered Status]

**Comment by ColmDC** [comment]
csv data looks clean. Other than the url trimming, did you need to do any cleaning ot our end?

**Comment by ColmDC** [comment]
What's still to do to complete the map, (seperately from the change request side?).

**Comment by wu-lee** [comment]
No trimming beyond the URIs.

Outstanding:
- Data feed needs to supply IDs instead of labels for taxonomy fields
- Corresponding indexes for IDs to labels need to be supplied and converted into vocab indexes
- We probably need to know if we should filter out any rows by (say) status - currently Registered Status of "Dead" is omitted, historical reasons, nothing else.
- I'm not sure if we have agreed the content of the pop-ups but if not that needs doing
- ditto about page
- ditto filterable fields
- ditto searchable fields

**Comment by ColmDC** [comment]
> * I'm not sure if we have agreed the content of the pop-ups but if not that needs doing
> 
> * ditto about page
> 
> * ditto filterable fields
> 
> * ditto searchable fields

See https://docs.google.com/document/d/1WkHl4oGmb3dtkcsdUqlGBx_mq9nWP1AoJNLd0-9HPc8/edit?usp=sharing

**Comment by ColmDC** [comment]
> * Data feed needs to supply IDs instead of labels for taxonomy fields
> 
> * Corresponding indexes for IDs to labels need to be supplied and converted into vocab indexes
> 
> * We probably need to know if we should filter out any rows by (say) status - currently Registered Status of "Dead" is omitted, historical reasons, nothing else.

These are all in Graham's court? Does he know exactly what he needs to do?

**Comment by wu-lee** [comment]
First two points yes, explicitly discussed at last meeting. Last one is on us, we just need to ask what to filter.

**Comment by wu-lee** [comment]
I've now gotten the dev.lod.coop redirector to work for worker-coop URLs. Required a small hack and an update of the Apache deployments to support that, in that the assumption to date was that all the URLs being redirected were on the same target domain, whereas now we're transitioning from (dev.)data.solidarityeconomy.coop to (dev.)data.digitalcommons.coop. This was set in the Apache config.

(While I was there I added support for ncba URLs; dotcoop2023 URLs were the other ones missing but they're now no longer used)

**Comment by ColmDC** [comment]
> Required a small hack and an update of the Apache deployments to support that, in that the assumption to date was that all the lod.coop URLs being redirected had the same target base URL, whereas now we're transitioning from (dev.)data.solidarityeconomy.coop to (dev.)data.digitalcommons.coop that's not true. This base URL was set in the Apache config.

When you say 'hack' do you infer it is creating tech debt, or that you needed to do something non standard on the server? I think we may now always redirect from lod.coop to multiple domains?

**Comment by wu-lee** [comment]
Not sure, you could look at it either way...

To explain: the workers-coop data is put on dev.data.digitalcommons.coop, and pretty much everything else is still on dev.data.solidarityeconomy.coop.  But will get moved across at some point.

lod.coop was configured such that only one base target URL was set; now we need to be able to have two so that workers-coops can be redirected to DCC, whilst the others stay the same.

It's a hack in that it wouldn't normally be necessary if we weren't transitioning from SEA to DCC domains, and everything could be in the same category.  It's not a massive change, but I'll need to revert to that situation when the transition is fully done and all data is on DCC servers - unless for some reason we *do* need to spread our data across multiple domains (so far as I know we won't).

Note, we have another category of redirect for ESSGLOBAL links. This hasn't changed. We could have more, but we don't currently redirect anything else.

**Comment by ColmDC** [comment]
I can confirm map at 

I've given the remaining subtasks [above](https://github.com/DigitalCommons/mykomap/issues/207#issuecomment-1836440395)  
tickboxes.

**Comment by ColmDC** [comment]
What update trigger are we using for this data set?

**Comment by wu-lee** [comment]
Just me on the keyboard currently

**Comment by ColmDC** [comment]
> Just me on the keyboard currently

I recall they had a low expection of frequency of updates, but is there any reason we wouldn't do it next to live?

**Comment by wu-lee** [comment]
By default it would be updated every 10 mins, same as the limesurvey maps. W.C.'s feed doesn't show any info about the last changes.

**Comment by ColmDC** [comment]
Progress blocked by third party inactivity, so moving into backlog until unblocked.

**Comment by wu-lee** [comment]
The data feed from workers.coop has now been updated by Graham. I've gone through the old CSV field descriptions I had and compared with the new, amending where necessary.

Some questions which came out of that process, with Graham's answers.

> Answers in and amongst below:
>

**Comment by wu-lee** [comment]
The data conversion alterations for the aforementioned changes are now done, and the new dataset deployed here:

  https://dev.data.digitalcommons.coop/workers-coop/
  https://dev.data.digitalcommons.coop/workers-coop/standard.csv

The map here will show that data now, but the pop-up fields still need to be added.

https://dev.maps.coop/workers-coop/

Next step is https://github.com/DigitalCommons/mykomap/issues/233

**Comment by wu-lee** [comment]
On this point:
> We probably need to know if we should filter out any rows by (say) status - currently Registered Status of "Dead" is omitted, historical reasons, nothing else.

Graham Mitchell suggests:
> My opinion - don’t show orgs that are not actively trading, so I would only show ‘Live’ records.

This is what we currently do...

But John Atherton suggests:
> We want the ability for people to see "non-live" records on the map, so they can let us know their status as this is one of the main data errors we have.
>
> But, the default view on the map, should be to only show the lives ones, I assume it is possible though to filter by different things and have one set as the default?
> 

This isn't possible in Mykomap - yet.

**Comment by ColmDC** [comment]
> This isn't possible in Mykomap - yet.

We need to implement https://github.com/DigitalCommons/mykomap/issues/205

**Comment by ColmDC** [comment]
@wu-lee just checking there is no reason this isn't in In Progress? Moving it there as I'm pretty sure it is active.

**Comment by wu-lee** [comment]
See #239 for final touches on this,
