### ISSUE TITLE
International Co-op Day Marker not renedring properly on narrow screens

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#211]
Custom markers are not renedring properly on narrow screens, https://github.com/DigitalCommons/dotcoop-project/issues/38#issuecomment-1597689693

Try reducing size to 1/2 current width.

**Comment by wu-lee** [comment]
Fixed I think, see https://github.com/DigitalCommons/dotcoop-project/issues/38#issuecomment-1607361361

**Comment by ColmDC** [comment]
WOrking now. Nice. I still think they are a bit big. Can you reduce them anyway, or is that a faf?

**Comment by wu-lee** [comment]
I've reduced the size, and also suppressed the old pin shadow, which looks even more weird with the smaller the pin icon.

I do notice that the markers don't contrast well when the map is zoomed in, as there are lots of roads marked in red.

We could either:
- change the logo colour, and hope there's nothing else with that colour to interfere
- add an outline, a "speech bubble" background, or something similar

I think the latter is more likely to work reliably.

**Comment by ColmDC** [comment]
Clients are happy with markers, so closing
