### ISSUE TITLE
Co-ops UK Map not working on some versions of Safari and Macs

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#212]
**Describe the bug**
No map is renedered on some versions of Safari and Macs

**To Reproduce**
1. Go to https://dev.coopsuk.solidarityeconomy.coop/
4. You see 
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/63665589a74876241a832285/4f07601f-aaee-4dc4-b206-a9429af184a9)

**Expected behavior**
You should see a map of UK with 1000s of co-ops.

**Desktop (please complete the following information):**
 - Mac OS Monterey 12.3
 - Safari - Version 15.4

**Smartphone (please complete the following information):**
No observed problems on IPhones.

**Additional context**
No observed problems on Mac OS Ventura 13.3.1.(a)/Safari 16.4

**Comment by ColmDC** [comment]
Awaiting spec of machine with symptoms. Can you provide instructions for user to generate a log? @wu-lee

**Comment by ColmDC** [comment]
@wu-lee Or schedule a call with Lance and get him to screen share and you can guide him to display the logs/console?

**Comment by wu-lee** [comment]
I've appropriated my partner's old macbook. I can reproduce the error.  It seems to be a Javascript exception:

> syntax Error: Invalid regular expression: invalid group specifier name - obj-transformer.ts:527

Which means that Safari doesn't support this:

        this.splitRx = new RegExp(`(?<!${escape.replace('\\', '\\\\')})${delim.replace('\\', '\\\\')}`);

I think that'd be specifically `(?<!..)` - negative look-behind.  The intention is to split a string on a CSV field delimiter, but not if it's escaped by the preceding character.  This is hard do do without negative look-behind.

Safari - IE for the 2020s.  Such a pain. Searching confirms this isn't supported:

https://stackoverflow.com/questions/68665498/make-regex-safari-compatible-by-removing-negative-lookbehind

Fixing this will need a bit of a think.

**Comment by ColmDC** [comment]
OS and browser version first showing problem added to opening description, but you have replicated it so less relevant.

**Comment by wu-lee** [comment]
I've reimplemented the field splitting without the use of a regular expression.

This works ok my browser.... bumping the coopsuk map and testing on Safari - yep seems to work there too.  This in v3.0.7, which should now be deployed on dev and prod coopsuk, and the dev version of dotcoop (the prod version is still on an old release of mykomaps).

**Comment by ColmDC** [comment]
Lance/DotCoop are testing.
