### ISSUE TITLE
Transfer and Upgrade Thunderforest account

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#214]
**Is your feature request related to a problem? Please describe.**
To date we have been using a free account with the tile service Thunderforest. It is also still in an account with SEA. We have had a significant increase in demand on the service and they have requested we upgrade. 

**Describe the solution you'd like**
Open a DCC account with Thunderforest on the lowest tier paid plan. Generate a new API key and start using it for all MykoMaps

**Describe alternatives you've considered**
Non considered

**Additional context**
We haven't reviewed tile server options for some time. Might be worth scheduling a review at some point, but it seems reasonable to at least pay for a few months before considering switching, service given how long we have used their free service.

Message from their admin below.

I've been looking at the requests on your account and we need to upgrade your account to a paid plan. Your current monthly quota period started on 18 June and since then you've made 262,613 requests. Your current Hobby Project plan includes a quota of 150,000 requests per month, which you've now exceeded.

Here are some details of the requests made in the past few days:

2023-07-02 | 11,190
2023-07-01 | 31,058
2023-06-30 | 48,057
2023-06-29 | 41,702
2023-06-28 | 37,214
2023-06-27 | 55,664
2023-06-26 | 7,230
2023-06-25 | 4,450
2023-06-24 | 1,519
2023-06-23 | 5,002
2023-06-22 | 3,619
2023-06-21 | 4,842
2023-06-20 | 3,857
2023-06-19 | 3,801
2023-06-18 | 3,408

To upgrade your account to the Solo Developer plan, please sign in to your Thunderforest account at:

https://manage.thunderforest.com/

There you can add or change your payment cards and invoicing details, and upgrade your account to the Solo Developer plan.

**Comment by ColmDC** [comment]
I commited to them that we would complete the transfer this month.

**Comment by ColmDC** [comment]
API Key and account details in BitWarden.

**Comment by wu-lee** [comment]
This is now updated and deployed in:
- ICD map
  -  https://dev.maps.solidarityeconomy.coop/icd/
- ICA map (also updated the prod branch to MM 3.0.7)
  -  https://dev.ica.solidarityeconomy.coop/
  -  https://ica.solidarityeconomy.coop/
- dotcoop map
  - pending
- mutual-aid map
  - pending

**Comment by ColmDC** [comment]
>(also updated the prod branch to MM 3.0.7) 
:-/ I expect ICA will notice the non localised names for the filters. What was in the previous about box? What else might they notice?...

**Comment by ColmDC** [comment]
Pushing to prod needs QA first.

**Comment by wu-lee** [comment]
Ok - reverted.

about.html has been gone since before the last production deploy version - the content was supplied by older defaults which have been removed.

**Comment by ColmDC** [comment]
> the content was supplied by older defaults which have been removed.

What do you mean by that?

**Comment by wu-lee** [comment]
If you look at the ICA map's about page now - there is no about.html custom text, and all of that text is boilerplate generated by the MM code. The text is a distillation of the common part which all the maps said up until that point. The code had translations for several languages, and inserted a link to the data source generated from the config.  Any custom text which exists in about.html provided gets inserted above that boilerplate.

But this feature was removed, for reasons I can't pin down right now. So the MM v3.0.7 ICA map has no about text, as there no boilerplate any more.

I have had a hunt for the issue relating to this removal, without total success: I recall there being a problem with the text and you essentially saying "remove it all". These aren't that, but seem to be fairly closely related:
- https://github.com/DigitalCommons/mutual-aid-project/issues/2#issuecomment-923751083
- https://github.com/DigitalCommons/mykomap/issues/125

**Comment by ColmDC** [comment]
Noted changes to how about panel is generated. I think that panel needs a review as part of the move make MMs more easily configurable. Further discussion on this thread however doesn't male sense.

**Comment by ColmDC** [comment]
> male sense.

or female sense.

**Comment by wu-lee** [comment]
Ok, ICA, DotCoopp and Mutual Aid API keys fixed, details will be updated in the comment above.

Incidentally - I note that the bot DotCoop maps have a French co-op floating a few hundred miles off the coast of Madagascar

**Comment by ColmDC** [comment]
>French co-op floating a few hundred miles off the coast of Madagascar

It's probably a French protectorate. Reunion perhaps?

**Comment by wu-lee** [comment]
Ah yes - zoom in and it is an island.

**Comment by ColmDC** [comment]
How can I test this? If Thunderforest disable the SEA API, will any of the maps no lonfer have tiles?

**Comment by wu-lee** [comment]
I tested it by opening the browser's developer console and checking the tileserver query URLs in the network panel have the right API key.

I suppose you could also go to shipshape and check the maps' config JSON there - they should also show the API key in the tileserver URL. But the above is a more definitive check that it is actually being used.

As for what happens if the old API key is disabled - I did a text search on locally checked out projects which use the thunderforest tiles, and the ones above are the ones I found.  I don't think there are any maps I've not got checked out here. Again, the important ones will be on shipshape, and they will show the tileserver URL - if it's not there the default is to use OpenStreetMap.

**Comment by ColmDC** [comment]
> not there the default is to use OpenStreetMap. 

Do you mean there is a free OSM tileserver avaialbe as well. If so, can you point me to it?

**Comment by wu-lee** [comment]
The default tileserver URL is `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` #

The service is the first one in the table here:

https://wiki.openstreetmap.org/wiki/Raster_tile_providers
