### ISSUE TITLE
Allow configuration of leaflet's minZoom setting

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#217]
**Is your feature request related to a problem? Please describe.**
DotCoop have asked that the limit to the map's zooming out be reduced. This is the "minimum" zoom level. There are no configurations which set this currently, and it seems to be hardwired at 2.

**Describe the solution you'd like**
Allow a `minZoom` setting in the MykoMap config which allows this to be set to a non-default value. Document this.

Leave the default at 2, for backwards compatibility.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by ColmDC** [comment]
Has this functionality been added to the documentation?

https://github.com/DigitalCommons/mykomap/blob/master/CONFIG.md

**Comment by wu-lee** [comment]
> Has this functionality been added to the documentation? @wu-lee
> 
> https://github.com/DigitalCommons/mykomap/blob/master/CONFIG.md

It has, but it's still only on the `dev` branch: https://github.com/DigitalCommons/mykomap/blob/dev/CONFIG.md#minzoom
