### ISSUE TITLE
Selecting an marker leaves it black

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#219]
**Describe the bug**
If you select a marker, it goes a little greyer as expected as he dialog is displayed. However if you click away or change the context in another way it turns black and stays black. 

**To Reproduce**
1. Go to https://dev.maps.solidarityeconomy.coop/mesopotamia/
2. Click on the most notherly co-op visible
3. Click anywhere else on the map.
4. It is black!

**Expected behavior**
It should return to the original colour it had before selection,

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTlmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fbc338d76b7e8052c5eb2f63b5bed150b370a438/blackicon.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 117.0
 - mykomap@3.0.9

**Additional context**
Also visible on https://dev.maps.solidarityeconomy.coop/monitor2022/

**Comment by ColmDC** [comment]
Checking older builds like 
https://dev.oxford.solidarityeconomy.coop/ which is mykomap@3.0.8
the markers don't go black, but turn red! Seems very likely to be connected.

Not replicatable on mykomap@3.0.7

**Comment by ColmDC** [comment]
Error visible on https://dev.maps.solidarityeconomy.coop/temp/dotcoop2023/?searchedFields=name,web on Chrome on Windows 10 mykomap@3.1.0

but markers behave correctly on https://dev.maps.solidarityeconomy.coop/temp/demo-merge-map/ mykomap@3.1.0 on both FF and Chrome on windows.

**Comment by wu-lee** [comment]
What it looks like is:
- There's an old feature which implements selectable pins, now essentially unused. Clicking toggles the selection state.
- There's still remnants of old hardwirings of the pin colours to the `primaryActivity` field of the initiatives
- Some of this sets the pin colour to black when it is selected but `primaryActivity` is unset.

Therefore, when we click a pin which has no primary activity it goes black.  I think the code to reset the colour, or set it to other colours, is however being removed progressively and mostly broken.

For now I'm just removing the style which makes the ping go black, and I'll leave the refactoring of the logic to the issues in this epic:

https://github.com/DigitalCommons/mykomap#workspaces/megaboard-639bb01fc526ef0010ab662b/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzMTE2

**Comment by ColmDC** [comment]
Fixed in mykomap@3.1.2 on ncba and mesopotamia
