### ISSUE TITLE
Allow a specific panel to be opened by default

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/mykomap#227]
## Problem 
Owned by Oxford (and some other projects) would like a mykomap to start. not only with the sidebar open, but with a specific panel active.

In ObO's case, they'd like the about page to be shown, with some help for new visitors.

In other cases, they'd like the search panel to be showing.

## What happens now

Currently, the panel can be opened by default (although see #226), but it always shows the directory (unless the directory is not enabled). If the directory is not enabled, it defaults to another panel (presumably the next in the list, left-to-right).

## Proposed solution

Implement a config option which selects the panel to open by default, if the sidebar is opened.  Possibly this could be the same option `defaultOpenSidebar` but with a string identifying the panel instead of merely a boolean `true` or `false` value.

**Comment by ColmDC** [comment]
See https://github.com/DigitalCommons/mykomap/issues/231

**Comment by ColmDC** [comment]
Closed as dupliate of 231
