### ISSUE TITLE
Create Merge Map Demo Video

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#228]
**Is your feature request related to a problem? Please describe.**
It is difficult to explain how we create maps of data merged from different sources

**Describe the solution you'd like**
Create short video demonstrating different versions of co-op data merging based on NCBA data.
The NCB is a co-operative bank which is a member of the ICA and the NCBA and has a Dotcoop website. 

The video should show the user finding the co-op in each map, and showing the differences in location and how it is described. 

Then the first of the merge maps is displayed with an explaination of what data it is displaying. 
The following points need to be clearly made:
- how we use the .coop registration as the connection data
- how we can add in missing fields, like street name
- how the map configuration needs to define which data source has priority when multiple dsource of data are available

Then the second of the merge maps is displayed with an explaination of what data it is displaying. 
The following points need to be clearly made:
- as in the first merge map we can merge data from multiple sources
- in this case however we include the co-ops from all 3 sources, but only display a since marker for each co-op when we know it is the same co-op
- show an example of when that doesn't happen
 
** Dependencies
 - We need both merge maps to lay out the data in dialogs in the same format
 - We need both merge maps to be remerged using the latest data

**Comment by ColmDC** [comment]
Assigning you here Nick until you have updated the data and the dialog layouts. I can do the video itself.

**Comment by wu-lee** [comment]
The data has been updated by re-running the scripts (although I needed to remove the duplicate IDs in the latest ICA data which was build locally courtesy of https://github.com/DigitalCommons/ica-project/issues/37)

If you need to inspect, it's at https://dev.maps.coop/demo-merge-map/left-ncba-dc-ica.csv

**Comment by ColmDC** [comment]
Okay, but it's not using the DotCoop street address for the geocoding.

**Comment by ColmDC** [comment]
https://dev.maps.coop/demo-merge-map-plus/ has also stopped loading. Spinning circle of death.

**Comment by ColmDC** [comment]
"Have been attempting to track down the source of this (although there have been distractions like childrens' birthdays)
Various things. First thing is that there was a line commented out in the merging script which prevented the new ICA data being loaded into it. (The ICA data is different because it didn't used to be published in CSV, so the script grabbed it from the adjacent open-data project working directory) 
Then the ICA's inclusion of duplicate IDs prevented the merge from working. Luckily they released their non-duplicated feed yesterday, and can use the published CSV from that now it's being generated
The CSV empty fields manifesting as '' and not NULLs in the database are now cleaned up into NULLs, which allows the coalesce() function to select the first non-null as intended
So now I can see, although it's a bit labourious to unpick, that the merge is doing what its' written to: It picks the first non-null geolocation out of a priority list: ICA, DC, then NCBA data."

**Comment by ColmDC** [comment]
Have you checked that NCB is now positioned correctly in https://dev.maps.coop/demo-merge-map-plus/  ?

**Comment by ColmDC** [comment]
Video was recorded and can be found [here](https://drive.google.com/file/d/18Ho7vn_k55K8ZMuLH8nxJ_WmE2H5w4as/view?usp=drive_link).
