### ISSUE TITLE
[Workers.coop] Complete evaluation of MM->CiviForm change request process

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#234]
**Please track against the clockify project [[Workers.coop](https://app.clockify.me/projects/65e883805590595c3ff37cdb/edit)]**

## Description
Confirm that the CiviCRM form generated by Workers.coop works fully and the complete range of required data types can be used to prepopulate it correctly.

The form can be found here... 

## Acceptance Criteria
- The following data types can be prepopulated with data available about the respective co-ops within a MykoMap 
  - Text
  - Single choice categories
  - Lat/Long
- The user can change each of the form field types
- When a field offers a single choice option, only supported options are presented
- The form does not attempt to submit to CiviCRM if an error is present in any of the fields.  
- The appropriate error message is presented when a field contains an unsupported entry when submission is attempted.
- The form cannot be submitted until the user has ticked the Open Data Approval.
-  The thank you message is visible for 2 seconds before the form closes and context returns to map.

**Comment by wu-lee** [comment]
> The form can be found here...

There isn't currently a working form, but here is a screenshot of the form as it was when last tested.

The problem this screenshot was taken to illustrate was that fields are not populating as expected. You can see the URL used in the console - I employed a hack to allow the form to work when embedded in a map hosted on `localhost:8080`. The URL parameters are what are significant: they're name/value pairs. For example, the parameter `email` is set to `contact@example.com` which means that the form should have that address pre-populated in the email text field. But it has not, and the console has a diagnostic from the CiviCRM form code showing the values it's picked up. And that says that `email` is taken from an empty `url_query_param`, and is not set to the value `<empty string>`.

![Screenshot_20231004_141922](https://github.com/DigitalCommons/mykomap/assets/67825/036a7316-15f4-4948-9bb9-22c3bfa06761)

**Comment by wu-lee** [comment]
Regarding this requirement:
> - The following data types can be prepopulated with data available about the respective co-ops within a MykoMap
>     * Text
>     * Single choice categories
>     * Lat/Long

- Text: we might need to support both short (single line) and long (multi-line) forms
- Single-choice categories:  
  - We probably need support for single and multiple in the general case (not sure about the worker.coop case specifically, would need to check the field list)
  - We should distinguish between selection using the displayed text and the symbolic ID for that value. If both are unique, they may both work, but the former is not so convenient, especially when embedded in an URL. 
  - In either case, the allowed values should match the values used in the map data, or else some programmatic way that the map software can map them needs to be defined. e.g. Are they URIs? Integers? Which ones?
- Lat/Long: presume this means just (a pair of) numeric values, not a map pin.

Another value which needs to be prepopulated, whilst still being a hidden value, is the organisation ID (AKA contact ID). 

If the form is to perform validation before submitting, some of the fields need more precise types. Specifically, we may need the field types for URLs, and email addresses.  I think CiviCRM's form supports those... but need to check.

**Comment by ColmDC** [comment]
> Reading the issue #221, validation of the lengths of digits seems to be mandated, error messages, and a submission prompt followed by automatically closing the form window - but it's not clear if CiviCRM's form module supports these.

Clear we shouldn't proceed with #221 until we have completed the evaluation.

**Comment by ColmDC** [comment]
Looks like this might be getting simplified by the client, so all the prefilling is managed by CiviCRM, and all the MM needs to do is pass the ID of the co-op whose details are being modified. See https://github.com/DigitalCommons/mykomap/issues/247

**Comment by lin-d-hop** [comment]
This issue is outdated, see #247
