### ISSUE TITLE
[OBO MykoMap] Support explicit configurabilty of field used in Directory panel 

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#237]
**Please track against the clockify project [[OBO MykoMap](https://app.clockify.me/projects/65e885153676853154ffc5ab/edit)]**

## Description
Add the ability to explicitly specify what field is used in Directory panel in the map configuration. At the moment it is implicit and assumed to be the top field displayed in the Search panel. Implementation needs to be backwards compatible, and if no configuration specified, the top field in the filter is defines the choice of field in the Directory panel.

## Acceptance Criteria

- Demonstrate its use on the https://dev.maps.solidarityeconomy.coop/obo-public/ map, where the Nature of Organisation remains the top Filter option, but Primary Activity is used in the Directory panel.
- Demonstrate backwards compatibilty on http://dev.maps.coop/ica

**Comment by ColmDC** [comment]
While addressing this consider what would happen if there are no filters defined.
It may cause an exception.  
Is it possible to disable the directory panel?

**Comment by lin-d-hop** [comment]
Hi @ColmDC,

A couple notes:
- The Acceptance Criteria sound more like testing notes. The actual acceptance criteria are dotted throughout the text.
- Its super helpful to give a little background. At least it helps me to unpack the jargon a bit faster.

Does the below correctly interpret what you've said?

##Description
Within MM the Directory panel is an expanded version of the first filter in the Search panel. In this issue we want to make it possible to specify another filter, besides the first one, as the filter to be expanded in the Directory panel. The goal is the create a new field that allows any of the filters from the Search panel to be selected, which can be specified in the MM config file.

##Acceptance Criteria
- Create an addition MM configuration option enabling a specified filter to be selected. This could be done by specifying an integer or text string, ideally readable yet flexible for any case.
- If this configuration is missing or throws an error, the default should be the first specified filter as now
- Ensure backwards compatibility with all MM (hopefully handled by the above)
- Ensure the case that no filters are defined is handled. Possibly by also not showing the directory. Or whatever happens now (ie backwards compatibility).

**Comment by ColmDC** [comment]
Perfect. Has anyone even mentioned that you are good at this @lin-d-hop?

**Comment by lin-d-hop** [comment]
Replaced by #248 (to save the time of other people reading through the comments)
