### ISSUE TITLE
Add Status as a filter to the Workers.coop filters

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#240]
**Please track this under [workers.coop] on clockify**

## Description
Add the [Status ](https://docs.google.com/document/d/1WkHl4oGmb3dtkcsdUqlGBx_mq9nWP1AoJNLd0-9HPc8/edit?pli=1#bookmark=id.2yh4uu944dq4)as a filter to the Workers.coop filters used.

In the the configuration settings set the default to be live.

In the data factory stop filtering out all the non Live co-ops.

## Acceptance Criteria

In dev,maps.coop/workers-coop check that the co-op with the title Glenwood Commodities Ltd is not discoverable on Startup 
In the Search panel change the Status filter option to display all co-ops. 
Check that Glenwood Commodities Ltd is now visible and has the Registered Status Dead

**Comment by ColmDC** [comment]
Currently blocked by https://github.com/DigitalCommons/mykomap/issues/205

**Comment by wu-lee** [comment]
This is now implemented and deployed as per https://github.com/DigitalCommons/mykomap/issues/205#issuecomment-2027212267

- https://maps.coop/workers-coop/ - without feedback link (possibly usable for production)
- https://maps.coop/workers-coop/ - with feedback link (but to unimplemented form)
