### ISSUE TITLE
Design caching for multiple cross database queries

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/mykomap#25]
Single data source queries can be easily cached. We need a solution to handle more complex queries that we expect ot be called a lot.
See [here](https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/209)

**Comment by ColmMassey** [comment]
"we need to fix some issues with server permissions before we can make the cache to update itself routinely."

**Comment by dtmakm27** [comment]
This issue is connected to how we solve this: https://github.com/SolidarityEconomyAssociation/open-data/issues/9

They will/should use some of the same code for checking for changes to the databases
