### ISSUE TITLE
[CWM] Create datasets for preliminary tests of large data in MM

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap#253]
** Please track this issue under Cooperative World Map **

## Description
The CWM project is asking for a larger set of data to be displayed in MM than we currently load into any MM. This issue is about creating some fake data sets so that we can start to explore the limits of what a MM can currently do.

To begin we're going to create datasets with only Name and Location in them. We'll create a few different sizes. As these explorations progress we'll likely make use of this code again to generate sets with more fields - description, categories etc. So it will be worth adding yourself some comments in the code for when you come back to it ;)

## Acceptance Criteria
- Create a simple script to create datasets that can be imported into MM
- The script should generate Name and Location (lat long?) data 
- Use the script to generate four files with the following number of datapoints: 
-> 100,000
-> 250,000
-> 500,000
-> 1,000,000

## Additional Context
The CWM project is being explored in [this Miro](https://miro.com/app/board/uXjVNhSEjfw=/)
There are also a bunch of notes in [this GDoc](https://docs.google.com/document/d/1Zb6GyV7_QM6UW9yZtY-VAmKzJE-T3PGoVM9d0bOuJyE/edit?pli=1#bookmark=id.8gk0qxlnfxv3)

**Comment by wu-lee** [comment]
I've written a TS script which deterministically generates the data. Should be the same data every time, if you call it with the same parameters.  Just deciding where to commit that script...

**Comment by wu-lee** [comment]
I've committed it to the Mykomap repository for now. Creating new repository seems unwarranted at this point.

(See commit reference above)

**Comment by ColmDC** [comment]
Can you add a link here to where the data sets are deployed?

**Comment by wu-lee** [comment]
They're generated by Marcel, and then committed to the map source code in the `www/` directory. 

So you can get the CSV files directly from the repository here: https://github.com/DigitalCommons/cwm-test-maps/tree/main/www

These are deployed with the map, so you can access the deployed file by adding the right filename to the map URL: https://dev.maps.solidarityeconomy.coop/qa/cwm-test-maps/
