### ISSUE TITLE
[CWM] Create test maps with fake data

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap#254]
** Please track under Cooperative World Map **

## Description
In order to gain a deeper understanding of the scale of refactoring needed to develop on the CWM we need to deploy a map with some fake data. 

We've decided to deploy maps with only Name and Location data. This means:
- Turn off the Search panel functionality
- Turn off the Directory panel functionality
- When someone clicks a marker, there is no additional information to display.

Our goal is to understand if a map can load and run well with this bare minimum of data, but a large number of data points.

## Acceptance Criteria
Four new MMs spun up using the four different datasets generated in #253. We'll use these datasets for some manual investigations and also for some analysis.
In this issue please outline how we can find them, both the UI for manual testing and the backend server bits for tech analysis.

## Additional Context
The CWM project is being explored in [this Miro](https://miro.com/app/board/uXjVNhSEjfw=/)
There are also a bunch of notes in [this GDoc](https://docs.google.com/document/d/1Zb6GyV7_QM6UW9yZtY-VAmKzJE-T3PGoVM9d0bOuJyE/edit?pli=1#bookmark=id.8gk0qxlnfxv3)

**Comment by wu-lee** [comment]
Ok, maps with data are published here for testing:

https://dev.maps.solidarityeconomy.coop/qa/cwm-test-maps/

**Comment by lin-d-hop** [comment]
@wu-lee @ms0ur1s 
This is really great! Thanks for showing the initiative with smaller data sets.

Key priority now is https://github.com/DigitalCommons/mykomap/issues/256 so that we can gather enough data to make some calls on next steps at the in-person days :)

**Comment by wu-lee** [comment]
Source code for the maps here: https://github.com/DigitalCommons/cwm-test-maps
