### ISSUE TITLE
[CWM] Build a shared types library for MykoMap API

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap#270]
Created after whiteboard #267

### Description
Develop a shared types library to centralize and standardize the data types used across the MykoMap API. This will ensure consistency in how data structures are defined and used across different parts of the project (FE and BE).

### Objectives
- Create TypeScript definitions for all data models used in the API.
- Ensure these types are shared and reused by both the frontend and backend.
- Implement a versioning system for the types library to manage changes effectively.

### Acceptance Criteria
- A shared types library is created ready for integration into both the frontend and backend codebases.
- The library includes all necessary types for the current API design.
- Documentation on how to use and update the types library is provided.

**Comment by rogup** [comment]
This has been achieved by using a `ts-rest` contract, defined in the `@mykomap/common` library.

So the only thing left for this ticket is to add some documentation about how it works and how to update it. It probably makes sense for me to do this.

**Comment by rogup** [comment]
Docs have been added
