### ISSUE TITLE
Support selection of directory filter group category.

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/mykomap#52]
Through the config file it is currently possible to group initiatives in the directory either by Activity, Locality or Country. 

Support the ability to toggle between these supported options in the sea-map interface somthing like this...
![Untitled](https://user-images.githubusercontent.com/1162642/84374801-75725680-abd6-11ea-9438-8f59e744c148.png)

**Comment by ColmMassey** [comment]
Can you comment here @wu-lee or @dtmakm27 how the parameters are currently interpreted. Clearly we do support multiple (3 I think) options for the directory. Have they each been hacked in rather than a generic solution?

**Comment by wu-lee** [comment]
I couldn't comment at the moment, would have to dig into the code.

**Comment by ColmMassey** [comment]
See also comment https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/235#issuecomment-732939937

**Comment by dtmakm27** [comment]
@ColmMassey 

We do support the functionality, but we have not built the interface for it

**Comment by ColmMassey** [comment]
When we look at this again, can we support the option of combining two fields which use the same vocabulary. For example, if Primary Activity and Secondary Activities fields are present in the dataset, we should support a filter option to filter all initiatives that have an activity in Primary OR Secondary Activities.
