### ISSUE TITLE
Get Activity names using correct sparql query

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/mykomap#62]
We are not getting the Activity names in the correct linked data manner. Once we have upgraded the  virtuouso servers to support this, get the correct names using sparql query. 

https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/104

https://github.com/SolidarityEconomyAssociation/open-data-and-maps/issues/150#issuecomment-655406026

**Comment by wu-lee** [comment]
Also see https://github.com/SolidarityEconomyAssociation/open-data/issues/38
