### ISSUE TITLE
Update url argument option documentation

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/mykomap#87]
multiple field example

drop 'within'
explain how white space etc is handled
change activity to otherActivities
need a hidden panel with debug info

**Comment by dtmakm27** [comment]
>multiple field example
drop 'within'
explain how white space etc is handled
change activity to otherActivities


@ColmMassey 
revised the documentation: 
https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md#searchedfields


>need a hidden panel with debug info


What you can do is go into console mode and check what variables are being provided to the url (as shown in the picture):

![image](https://user-images.githubusercontent.com/34026440/102015515-14c60100-3d54-11eb-9770-b9b0b2d7ba9f.png)



![image](https://user-images.githubusercontent.com/34026440/102015528-27d8d100-3d54-11eb-8cfd-976524cb738a.png)


(Specifically for search)
You can check (also in the console) when clicking on an initiative the 'searchstr' attribute (i.e. check what actually got generated): 

![image](https://user-images.githubusercontent.com/34026440/102015618-99188400-3d54-11eb-85cb-442359730b20.png)






Not really sure what we else we can cover with a hidden panel?

**Comment by ColmMassey** [comment]
> Not really sure what we else we can cover with a hidden panel?

What I meant was log panel which would output errors like unrecognised url parameters. Something for the future...

**Comment by ColmMassey** [comment]
Are regorg and orgStructure the same?

WHat's up with the spacing in the docs?

Can you point to the code which interprets the arguments and assignes them to fields to be searched?

**Comment by dtmakm27** [comment]
> Are regorg and orgStructure the same?


regorg - is only the first organisational structure we have for a particular initiative
orgStructure - is a list of all organisational structures that we have for a particular initiative

>WHat's up with the spacing in the docs?


Could you point to an example or a link to the docs so i can check them? 



> Can you point to the code which interprets the arguments and assignes them to fields to be searched?


https://github.com/SolidarityEconomyAssociation/sea-map/blob/f3e4badf394084e9996026f70649f8350aca8b72/www/map-app/app/model/sse_initiative.js#L229

**Comment by ColmMassey** [comment]
There is still an issue with whitespace and fullstops in the documentation.

**Comment by ColmMassey** [comment]
Happy to close once that is sorted.

**Comment by King-Mob** [comment]
@ColmMassey would you like me to take on the documentation task?

**Comment by ColmMassey** [comment]
Makes sense as you are in _search_ land.
